FROM node:18
WORKDIR /app
COPY package*.json ./
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*
RUN npm install
COPY . .
COPY src/services/booking/wait-for-mysql.sh ./wait-for-mysql.sh
RUN chmod +x ./wait-for-mysql.sh
CMD ["./wait-for-mysql.sh", "mysql", "node", "server.js"]
